### ISSUE TITLE
[회원가입] 동일계정 가입 가능 이슈

### ISSUE THREAD

**Issue by nightohl** [Kimyechan/DivingProject-BackEnd#14]
회의 때 나왔던 이슈사항 기록

- 회원가입 시 동일 메일로 가입 가능
- 중복계정 로그인 요청 시 쿼리가 유니크한 리턴값을 반환하지 않는다는 에러

![image](https://user-images.githubusercontent.com/48432932/111069477-94f53180-8510-11eb-9313-935c2e8da88e.png)

**Comment by Kimyechan** [comment]
중복 체크 완료 했습니다
중복계정 로그인은 기존 DB에 있는 중복 이메일 정보를 제거하고 실행해주세요
