### ISSUE TITLE
[일정조회] 일정이 조회되지 않는 현상

### ISSUE THREAD

**Issue by nightohl** [Kimyechan/DivingProject-BackEnd#16]
### api 변화
- 기존 : 강의 등록 시 max 인원을 전달
- 새로운 api : 일정 등록 시 max 인원을 전달

### 문제사항
api 변경에 따른 프론트 로직 수정 후, 이를 반영하고자 db를 drop 후 다시 생성했더니
강의등록, 일정등록은 잘 됐는데, 일정 조회 api 요청 시 200 response를 받고 데이터가 아무것도 반환되지 않는 현상.
db를 살펴보면 데이터는 잘 들어가 있음.

확인 필요 !

![image](https://user-images.githubusercontent.com/48432932/111077745-9553f380-8535-11eb-97ca-6fe4604e88b0.png)
![image](https://user-images.githubusercontent.com/48432932/111077813-e1069d00-8535-11eb-8b44-f953723d22cf.png)

**Comment by Kimyechan** [comment]
지나간 날짜 일정은 조회되지 않습니다
