### ISSUE TITLE
[문서][강의등록] 필요없는 필드 남아있음.

### ISSUE THREAD

**Issue by nightohl** [Kimyechan/DivingProject-BackEnd#32]
### 강의등록 시 필요없는 필드
* `period`
* `studentCount`
두 필드는 일정마다 달라질 수 있으므로 일정등록 시 기재하는 것으로 변동 및 반영된 상태.
하지만 도큐먼트를 보면 아직 필드가 남아있고, 강의단건 상세조회 시에도 두 필드가 null null로 반환되고 있음.

두 값을 전달하지 않고도 강의가 생성되므로 큰 문제는 아님.
우선순위는 낮음.

![image](https://user-images.githubusercontent.com/48432932/112726727-4741e580-8f62-11eb-9ba1-ae67ea0c6481.png)

**Comment by Kimyechan** [comment]
수정 완료했습니다
