### ISSUE TITLE
[문서] 유저부분 문서화 부분 생략됨 (?)

### ISSUE THREAD

**Issue by nightohl** [Kimyechan/DivingProject-BackEnd#35]
테스트 코드를 돌려도 유저 관련 API 도큐먼트 부분만 생략됨.
기존에 사용하던 api 양식으로 참조 가능하므로 우선순위는 낮아도 됨.

강사권한 추가 양식 보려다가 발견!

> 유저 생성
No snippets found for operation::signUp

> 유저 로그인
No snippets found for operation::signIn

> 강사 권한 및 강사 정보 추가
No snippets found for operation::sign-addInstructorRole

> 토큰 재발급
No snippets found for operation::refresh

> 유저 로그아웃
No snippets found for operation::logout

**Comment by Kimyechan** [comment]
./gradlew build를 입력해서 빌드를 다시 진행시킨 후에 확인 부탁드립니다
